server:
  port: 8189
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
jwt:
  lifetime: ${JWT_LIFETIME:3600000}
  secret: ${JWT_SECRET:}